### ISSUE TITLE
Multiple duplicated onclick events attached to links

### ISSUE THREAD

**Issue by rob006** [club-1/flarum-ext-cross-references#39]
> > Note that #31 contains one minor fix that prevents attaching multiple onclick events to links: [2d0642b](https://github.com/club-1/flarum-ext-cross-references/commit/2d0642bdeae14ca6294f3367c71f9b35d8df8fd7). It's not very elegant solution, but without it "back" button in browser did not worked correctly.
> 
> I can't seem to be able to replicate this issue. I didn't find instances of duplicated events and I didn't notice issues with the "back" button of the browser. Could please you open an issue with a reproducer?
> 
> _Originally posted by @n-peugnet in https://github.com/club-1/flarum-ext-cross-references/issues/36#issuecomment-1436113748_

I always have at least 2 events attached to links generated by this extension. 

![e613f66d](https://user-images.githubusercontent.com/5972388/220043890-3c9e203e-691a-4daa-a4f3-da9de2b9e1a5.png)

And new events are attached every time when I click on new post composer.

![0feeade4](https://user-images.githubusercontent.com/5972388/220043938-64c9d2f3-f128-4dda-bf97-f12e680e4970.png)

Probably `this.$('.Post-body a')` is not a correct way to scope links for specific post. Maybe something like `$(this).find('.Post-body a')` will work?

**Comment by n-peugnet** [comment]
It seems the [`onupdate()` function](https://api.docs.flarum.org/js/v1.6.0/classes/forum_components_commentpost.commentpost#onupdate) is called a lot more often than what I thought. I think I will go for your fix for now.

**Comment by n-peugnet** [comment]
Let me know if you would like me to release a `v1.0.4` version just for this fix.

**Comment by rob006** [comment]
It is not super urgent, I think it can wait for next release.

**Comment by n-peugnet** [comment]
In the meantime, you could still use the `dev-main` composer version. I compiled the assets in production mode in this eventuality.

**Comment by n-peugnet** [comment]
Well, I won't have much time to work on this extension for some days so I will just release a version with this fix now
